services:
  - type: worker
    name: render-subnet-router
    env: docker
    autoDeploy: false
    envVars:
      - key: TAILSCALE_AUTHKEY
        sync: false
      - key: TAILSCALE_VERSION
        value: 1.102.4
      - key: TCP_FORWARDS
        value: 8123=plausible-events-db:8123
    disk:
      name: tailscale-state
      mountPath: /var/lib/tailscale
      sizeGB: 1

